# Create logistic regression to predict

# import library

In [186]:
#coding: utf-8
import pandas as pd 
import numpy as np

# Create linear regression to predict absent

In [226]:
df_Absent=pd.read_csv("Absent_preprosessing.csv")
df_Absent.head()

,Reason1,Reason2,Reason3,Reason4,Month value,Day of week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,7,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,14,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,15,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,16,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,23,289,36,33,239.554,30,0,2,1,2

In [ ]:
#delete all the unname column
#df_Absent=df_Absent.drop(columns='Unnamed: 0')
df_Absent

# Create target (Choose which column is useful for the prediction)

In [ ]:
#find med to classify the consistantcy of absent (if>med : High absent), (if < med : Low absent)
med_abesnt=df_Absent["Absenteeism Time in Hours"].median()

In [ ]:
#create targets Extreamly high(1): Absent hour >= 4 Moderately High(0): Absent hour <=3
#target=[]
#for n in df_Absent["Absenteeism Time in Hours"]:
#    if n>3:
#       target.append(1)
#    if n<=3:
#       target.append(0)

#target=pd.DataFrame(target,columns=["Target"])


#or using >>>> where
target=np.where(df_Absent["Absenteeism Time in Hours"]>med_abesnt,1,0)
target

# Create new column

In [ ]:
df_Absent["Excessive Absenteeism"]=target
df_target=df_Absent.drop(columns="Absenteeism Time in Hours")
df_target

In [ ]:
#Y.shape is (n,m). So Y.shape[0] is n.
#find percentage of excessive absent
print((target.sum()/target.shape[0])*100,"%")

# Select inputs for regrssion

In [ ]:
df_target.shape

In [ ]:
unscale_input=df_target.iloc[:,0:14] #or df_input=df_target.iloc[:,:-1] would be more appropriate 
unscale_input

# Standardization

In [ ]:
from sklearn.preprocessing import StandardScaler 
#Standardize features by removing the mean and scaling to unit variance
#z = (x - u) / s
absenteeism_scaler=StandardScaler()
#StandardScaler() will normalize the features (each column of X) so that each column/feature/variable will have 
#mean = 0 and standard deviation = 1

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler
class CustomScaler (BaseEstimator, TransformerMixin):
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns=columns
        self.mean=None
        self.var=None
    def fit(self, X,y=None):
        self.scaler.fit(X[self.columns],y)
        self.mean=np.mean(X[self.columns])
        self.var=np.var(X[self.columns])
        return self
    def transform(self, X,y=None,copy=None):
        init_col_order=X.columns
        X_scale=pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scale=X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scale,X_scale],axis=1)[init_col_order]

In [ ]:
unscale_input.columns.values

In [ ]:
columns_to_scale=['Month value', 'Day of week', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'] #don't use dummies

In [188]:
unscale_input

,Reason1,Reason2,Reason3,Reason4,Month value,Day of week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,0,0,0,1,7,7,289,36,33,239.554,30,0,2,1
1,0,0,0,0,7,14,118,13,50,239.554,31,0,1,0
2,0,0,0,1,7,15,179,51,38,239.554,31,0,0,0
3,1,0,0,0,7,16,279,5,39,239.554,24,0,2,0
4,0,0,0,1,7,23,289,36,33,239.554,30,0,2,1
5,0,0,0,1,7,10,179,51,38,239.554,31,0,0,0
6,0,0,0,1,7,17,361,52,28,239.554,27,0,1,4
7,0,0,0,1,7,24,260,50,36,239.554,23,0,4,0
8,0,0,1,0,7,6,155,12,34,239.554,25,0,2,0
9,0,0,0,1,7,13,235,11,37,239.554,29,1,1,1
10,1,0,0,0,7,20,260,50,36,239.554,23,0,4,0
11,1,0,0,0,7,14,260,50,36,239.554,23,0,4,0
12,1,0,0,0,7,15,260,50,36,239.554,23,0,4,0
13,1,0,0,0,7,15,179,51,38,239.554,31,0,0,0
14,0,0,0,1,7,15,179,51,38,239.554,31,0,0,0
15,1,0,0,0,7,17,246,25,41,239.554,23,0,0,0
16,0,0,0,1,7,17,179,51,38,239.554,31,0,0,0
17,0,0,1,0,7,27,179,51,38,239.554,31,0,0,0
18,1,0,0,0,7,30,189,29,33,239.554,25,0,2,2
19,0,0,0,1,8,5,248,25,47,205.917,32,0,2,1
20,1,0,0,0,8,12,330,16,28,205.917,25,1,0,0
21,1,0,0,0,8,3,179,51,38,205.917,31,0,0,0
22,1,0,0,0,8,10,361,52,28,205.917,27,0,1,4
23,0,0,0,1,8,14,260,50,36,205.917,23,0,4,0
24,0,0,1,0,8,17,289,36,33,205.917,30,0,2,1
25,0,0,0,1,8,24,361,52,28,205.917,27,0,1,4
26,0,0,0,1,8,4,289,36,33,205.917,30,0,2,1
27,0,0,0,1,8,12,157,27,29,205.917,22,0,0,0
28,0,0,1,0,8,19,289,36,33,205.917,30,0,2,1
29,0,0,0,1,8,28,179,51,38,205.917,31,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,4,24,155,12,34,246.288,25,0,2,0
671,0,0,1,0,4,26,225,26,28,246.288,24,0,1,2
672,1,0,0,0,4,26,118,13,50,246.288,31,0,1,0
673,0,0,0,1,4,27,179,26,30,246.288,19,1,0,0
674,0,0,0,1,5,7,235,11,37,237.656,29,1,1,1
675,0,0,1,0,5,9,225,15,41,237.656,28,1,2,2
676,0,0,0,1,5,9,235,16,32,237.656,25,1,0,0
677,1,0,0,0,5,9,118,10,37,237.656,28,0,0,0
678,0,0,0,1,5,9,235,20,43,237.656,38,0,1,0
679,1,0,0,0,5,10,179,26,30,237.656,19,1,0,0
680,0,0,0,1,5,10,291,31,40,237.656,25,0,1,1
681,1,0,0,0,5,10,225,15,41,237.656,28,1,2,2
682,0,0,1,0,5,11,300,26,43,237.656,25,0,2,1
683,0,0,0,1,5,11,225,15,41,237.656,28,1,2,2
684,0,0,0,1,5,11,179,26,30,237.656,19,1,0,0
685,0,0,0,1,5,14,118,13,50,237.656,31,0,1,0
686,1,0,0,0,5,15,118,13,50,237.656,31,0,1,0
687,0,0,0,1,5,15,118,10,37,237.656,28,0,0,0
688,0,0,0,0,5,15,118,13,50,237.656,31,0,1,0
689,0,0,0,1,5,16,179,26,30,237.656,19,1,0,0
690,0,0,0,0,5,16,378,49,36,237.656,21,0,2,4
691,0,1,0,0,5,18,179,22,40,237.656,22,1,2,0
692,1,0,0,0,5,21,155,12,34,237.656,25,0,2,0
693,1,0,0,0,5,21,235,16,32,237.656,25,1,0,0
694,0,0,0,1,5,23,291,31,40,237.656,25,0,1,1
695,1,0,0,0,5,23,179,22,40,237.656,22,1,2,0
696,1,0,0,0,5,23,225,26,28,237.656,24,0,1,2
697,1,0,0,0,5,24,330,16,28,237.656,25,1,0,0
698,0,0,0,1,5,24,235,16,32,237.656,25,1,0,0
699,0,0,0,1,5,31,291,31,40,237.656,25,0,1,1

In [189]:
absenteeism_scaler=CustomScaler(columns_to_scale)

In [190]:
absenteeism_scaler.fit(unscale_input)

/Users/pinnytu/anaconda2/lib/python3.6/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)

CustomScaler(columns=['Month value', 'Day of week', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children', 'Pets'],
       copy=None, with_mean=None, with_std=None)

In [191]:
scale_input=absenteeism_scaler.transform(unscale_input) 
scale_input

/Users/pinnytu/anaconda2/lib/python3.6/site-packages/ipykernel_launcher.py:17: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.

,Reason1,Reason2,Reason3,Reason4,Month value,Day of week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,0,0,0,1,0.182726,-1.103121,1.005844,0.412816,-0.536062,-0.806331,0.767431,-0.447980,0.880469,0.268487
1,0,0,0,0,0.182726,-0.228337,-1.574681,-1.141882,2.130803,-0.806331,1.002633,-0.447980,-0.019280,-0.589690
2,0,0,0,1,0.182726,-0.103367,-0.654143,1.426749,0.248310,-0.806331,1.002633,-0.447980,-0.919030,-0.589690
3,1,0,0,0,0.182726,0.021602,0.854936,-1.682647,0.405184,-0.806331,-0.643782,-0.447980,0.880469,-0.589690
4,0,0,0,1,0.182726,0.896386,1.005844,0.412816,-0.536062,-0.806331,0.767431,-0.447980,0.880469,0.268487
5,0,0,0,1,0.182726,-0.728213,-0.654143,1.426749,0.248310,-0.806331,1.002633,-0.447980,-0.919030,-0.589690
6,0,0,0,1,0.182726,0.146571,2.092381,1.494345,-1.320435,-0.806331,0.061825,-0.447980,-0.019280,2.843016
7,0,0,0,1,0.182726,1.021355,0.568211,1.359154,-0.065439,-0.806331,-0.878984,-0.447980,2.679969,-0.589690
8,0,0,1,0,0.182726,-1.228090,-1.016322,-1.209478,-0.379188,-0.806331,-0.408580,-0.447980,0.880469,-0.589690
9,0,0,0,1,0.182726,-0.353306,0.190942,-1.277074,0.091435,-0.806331,0.532229,2.232242,-0.019280,0.268487
10,1,0,0,0,0.182726,0.521479,0.568211,1.359154,-0.065439,-0.806331,-0.878984,-0.447980,2.679969,-0.589690
11,1,0,0,0,0.182726,-0.228337,0.568211,1.359154,-0.065439,-0.806331,-0.878984,-0.447980,2.679969,-0.589690
12,1,0,0,0,0.182726,-0.103367,0.568211,1.359154,-0.065439,-0.806331,-0.878984,-0.447980,2.679969,-0.589690
13,1,0,0,0,0.182726,-0.103367,-0.654143,1.426749,0.248310,-0.806331,1.002633,-0.447980,-0.919030,-0.589690
14,0,0,0,1,0.182726,-0.103367,-0.654143,1.426749,0.248310,-0.806331,1.002633,-0.447980,-0.919030,-0.589690
15,1,0,0,0,0.182726,0.146571,0.356940,-0.330735,0.718933,-0.806331,-0.878984,-0.447980,-0.919030,-0.589690
16,0,0,0,1,0.182726,0.146571,-0.654143,1.426749,0.248310,-0.806331,1.002633,-0.447980,-0.919030,-0.589690
17,0,0,1,0,0.182726,1.396263,-0.654143,1.426749,0.248310,-0.806331,1.002633,-0.447980,-0.919030,-0.589690
18,1,0,0,0,0.182726,1.771171,-0.503235,-0.060353,-0.536062,-0.806331,-0.408580,-0.447980,0.880469,1.126663
19,0,0,0,1,0.468236,-1.353059,0.387122,-0.330735,1.660180,-1.647399,1.237836,-0.447980,0.880469,0.268487
20,1,0,0,0,0.468236,-0.478275,1.624567,-0.939096,-1.320435,-1.647399,-0.408580,2.232242,-0.919030,-0.589690
21,1,0,0,0,0.468236,-1.602998,-0.654143,1.426749,0.248310,-1.647399,1.002633,-0.447980,-0.919030,-0.589690
22,1,0,0,0,0.468236,-0.728213,2.092381,1.494345,-1.320435,-1.647399,0.061825,-0.447980,-0.019280,2.843016
23,0,0,0,1,0.468236,-0.228337,0.568211,1.359154,-0.065439,-1.647399,-0.878984,-0.447980,2.679969,-0.589690
24,0,0,1,0,0.468236,0.146571,1.005844,0.412816,-0.536062,-1.647399,0.767431,-0.447980,0.880469,0.268487
25,0,0,0,1,0.468236,1.021355,2.092381,1.494345,-1.320435,-1.647399,0.061825,-0.447980,-0.019280,2.843016
26,0,0,0,1,0.468236,-1.478029,1.005844,0.412816,-0.536062,-1.647399,0.767431,-0.447980,0.880469,0.268487
27,0,0,0,1,0.468236,-0.478275,-0.986140,-0.195544,-1.163560,-1.647399,-1.114186,-0.447980,-0.919030,-0.589690
28,0,0,1,0,0.468236,0.396509,1.005844,0.412816,-0.536062,-1.647399,0.767431,-0.447980,0.880469,0.268487
29,0,0,0,1,0.468236,1.521232,-0.654143,1.426749,0.248310,-1.647399,1.002633,-0.447980,-0.919030,-0.589690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,-0.673803,1.021355,-1.016322,-1.209478,-0.379188,-0.637953,-0.408580,-0.447980,0.880469,-0.589690
671,0,0,1,0,-0.673803,1.271294,0.040034,-0.263140,-1.320435,-0.637953,-0.643782,-0.447980,-0.019280,1.126663
672,1,0,0,0,-0.673803,1.271294,-1.574681,-1.141882,2.130803,-0.637953,1.002633,-0.447980,-0.019280,-0.589690
673,0,0,0,1,-0.673803,1.396263,-0.654143,-0.263140,-1.006686,-0.637953,-1.819793,2.232242,-0.919030,-0.589690
674,0,0,0,1,-0.388293,-1.103121,0.190942,-1.277074,0.091435,-0.853789,0.532229,2.232242,-0.019280,0.268487
675,0,0,1,0,-0.388293,-0.853183,0.040034,-1.006691,0.718933,-0.853789,0.297027,2.232242,0.880469,1.126663
676,0,0,0,1,-0.388293,-0.853183,0.190942,-0.939096,-0.692937,-0.853789,-0.408580,2.232242,-0.919030,-0.589690
677,1,0,0,0,-0.388293,-0.853183,-1.574681,-1.344669,0.091435,-0.853789,0.297027,-0.447980,-0.919030,-0.589690
678,0,0,0,1,-0.388293,-0.853183,0.190942,-0.668713,1.032682,-0.853789,2.649049,-0.447980,-0.019280,-0.589690
679,1,0,0,0,-0.388293,-0.728213,-0.654143,-0.263140,-1.006686,-0.853789,-1.819793,2.232242,-0.919030,-0.589690
680,0,0,0,1,-0.388293,-0.728213,1.036026,0.074838,0.562059,-0.853789,-0.408580,-0.447980,-0.019280,0.268487
681,1,0,0,0,-0.388293,-0.728213,0.040034,-1.006691,0.718933,-0.853789,0.297027,2.232242,0.880469,1.126663
682,0,0,1,0,-0.388293,-0.603244,1.171843,-0.263140,1.032682,-0.853789,-0.408580,-0.447980,0.880469,0.268487
683,0,0,0,1,-0.388293,-0.603244,0.040034,-1.006691,0.718933,-0.853789,0.297027,2.232242,0.880469,1.126663
684,0,0,0,1,-0.388293,-0.603244,-0.654143,-0.263140,-1.006686,-0.853789,-1.819793,2.232242,-0.919030,-0.589690
685,0,0,0,1,-0.388293,-0.228337,-1.574681,-1.141882,2.130803,-0.853789,1.002633,-0.447980,-0.019280,-0.589690
686,1,0,0,0,-0.388293,-0.103367,-1.574681,-1.141882,2.130803,-0.853789,1.002633,-0.447980,-0.019280,-0.589690
687,0,0,0,1,-0.388293,-0.103367,-1.574681,-1.344669,0.091435,-0.853789,0.297027,-0.447980,-0.919030,-0.589690
688,0,0,0,0,-0.388293,-0.103367,-1.574681,-1.141882,2.130803,-0.853789,1.002633,-0.447980,-0.019280,-0.589690
689,0,0,0,1,-0.388293,0.021602,-0.654143,-0.263140,-1.006686,-0.853789,-1.819793,2.232242,-0.919030,-0.589690
690,0,0,0,0,-0.388293,0.021602,2.348925,1.291558,-0.065439,-0.853789,-1.349389,-0.447980,0.880469,2.843016
691,0,1,0,0,-0.388293,0.271540,-0.654143,-0.533522,0.562059,-0.853789,-1.114186,2.232242,0.880469,-0.589690
692,1,0,0,0,-0.388293,0.646448,-1.016322,-1.209478,-0.379188,-0.853789,-0.408580,-0.447980,0.880469,-0.589690
693,1,0,0,0,-0.388293,0.646448,0.190942,-0.939096,-0.692937,-0.853789,-0.408580,2.232242,-0.919030,-0.589690
694,0,0,0,1,-0.388293,0.896386,1.036026,0.074838,0.562059,-0.853789,-0.408580,-0.447980,-0.019280,0.268487
695,1,0,0,0,-0.388293,0.896386,-0.654143,-0.533522,0.562059,-0.853789,-1.114186,2.232242,0.880469,-0.589690
696,1,0,0,0,-0.388293,0.896386,0.040034,-0.263140,-1.320435,-0.853789,-0.643782,-0.447980,-0.019280,1.126663
697,1,0,0,0,-0.388293,1.021355,1.624567,-0.939096,-1.320435,-0.853789,-0.408580,2.232242,-0.919030,-0.589690
698,0,0,0,1,-0.388293,1.021355,0.190942,-0.939096,-0.692937,-0.853789,-0.408580,2.232242,-0.919030,-0.589690
699,0,0,0,1,-0.388293,1.896140,1.036026,0.074838,0.562059,-0.853789,-0.408580,-0.447980,-0.019280,0.268487

In [192]:
#fit(X[, y])	Compute the mean and std to be used for later scaling
#transform(X[, y, copy])	Perform standardization by centering and scaling

#scale_input=absenteeism_scaler.fit_transform(unscale_input) 
#scale_input

In [193]:
scale_input.mean(axis=0) #mean close to 0

Reason1                    2.500000e-01
Reason2                    8.571429e-03
Reason3                    9.000000e-02
Reason4                    5.971429e-01
Month value               -3.868334e-16
Day of week                4.821540e-17
Transportation Expense    -1.703399e-16
Distance to Work           1.261689e-16
Age                        1.221245e-16
Daily Work Load Average    9.538402e-16
Body Mass Index            5.424232e-17
Education                  2.561443e-16
Children                  -1.058380e-16
Pets                      -2.973019e-16
dtype: float64

In [194]:
scale_input.std(axis=0) #std close to 1

Reason1                    0.433322
Reason2                    0.092250
Reason3                    0.286386
Reason4                    0.490823
Month value                1.000715
Day of week                1.000715
Transportation Expense     1.000715
Distance to Work           1.000715
Age                        1.000715
Daily Work Load Average    1.000715
Body Mass Index            1.000715
Education                  1.000715
Children                   1.000715
Pets                       1.000715
dtype: float64

# Split the data into train, test & shuffle

In [195]:
from sklearn.model_selection import train_test_split

In [196]:
X_train,X_test,y_train,y_test= train_test_split(scale_input,target)

In [197]:
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(525, 14) (525,)
(175, 14) (175,)

# Logistic regression with sklearn

In [198]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

Training the model

In [199]:
reg=LogisticRegression()
reg.fit(X_train,y_train)

/Users/pinnytu/anaconda2/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [200]:
#.score(inputs,targets) return mean accuracy on the given test data and labels
reg.score(X_train,y_train) #model learn to classify ~ 75% correctly

0.7619047619047619

# Manaully check the accuracy

In [201]:
model_output=reg.predict(X_train)
model_output

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0])

In [202]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1])

In [203]:
model_output == y_train

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True, False,  True, False,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True, False, False, False,
        True,  True, False,  True,  True,  True,  True,  True, False,
       False,  True, False,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True, False,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True, False,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True, False,  True, False, False, False,  True,
       False,  True,  True,  True,  True,  True, False, False,  True,
       False,  True,  True, False, False,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False,  True,  True, False,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True, False,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
       False, False,  True, False,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True, False, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False])

In [204]:
(np.sum(model_output==y_train)/model_output.shape[0])*100 #find TRUE %  #get the same result as using 'score '

76.19047619047619

# Finding intercept(b1) and coefficient(b2,b3..) of linear/logistic regression 
y=b1+b2X1+b3X2+b4X3+...

In [205]:
reg.intercept_

array([-1.52726691])

In [206]:
reg.coef_

array([[ 2.72561273,  0.72239116,  2.77112163,  0.76185256,  0.02839126,
        -0.05073325,  0.66812936, -0.05128134, -0.10428782,  0.02293065,
         0.2289355 ,  0.0692117 ,  0.35394673, -0.28900301]])

Create new table contain header of each column and intercept + coef in this order

In [207]:
feature_col=unscale_input.columns.values
feature_col

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month value',
       'Day of week', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [208]:
reg.coef_

array([[ 2.72561273,  0.72239116,  2.77112163,  0.76185256,  0.02839126,
        -0.05073325,  0.66812936, -0.05128134, -0.10428782,  0.02293065,
         0.2289355 ,  0.0692117 ,  0.35394673, -0.28900301]])

In [209]:
data={"Features": feature_col, "Coefficient": reg.coef_[0][:]}

In [210]:
summary_df=pd.DataFrame(data)
summary_df

                   Features  Coefficient
0                   Reason1     2.725613
1                   Reason2     0.722391
2                   Reason3     2.771122
3                   Reason4     0.761853
4               Month value     0.028391
5               Day of week    -0.050733
6    Transportation Expense     0.668129
7          Distance to Work    -0.051281
8                       Age    -0.104288
9   Daily Work Load Average     0.022931
10          Body Mass Index     0.228935
11                Education     0.069212
12                 Children     0.353947
13                     Pets    -0.289003

In [211]:
summary_df.index.values[1:14]
summary_df

                   Features  Coefficient
0                   Reason1     2.725613
1                   Reason2     0.722391
2                   Reason3     2.771122
3                   Reason4     0.761853
4               Month value     0.028391
5               Day of week    -0.050733
6    Transportation Expense     0.668129
7          Distance to Work    -0.051281
8                       Age    -0.104288
9   Daily Work Load Average     0.022931
10          Body Mass Index     0.228935
11                Education     0.069212
12                 Children     0.353947
13                     Pets    -0.289003

In [212]:
summary_df.index = summary_df.index + 1
summary_df.loc[0]=["Intercept",reg.intercept_[0]]

conclude_df=summary_df.sort_index()
conclude_df

                   Features  Coefficient
0                 Intercept    -1.527267
1                   Reason1     2.725613
2                   Reason2     0.722391
3                   Reason3     2.771122
4                   Reason4     0.761853
5               Month value     0.028391
6               Day of week    -0.050733
7    Transportation Expense     0.668129
8          Distance to Work    -0.051281
9                       Age    -0.104288
10  Daily Work Load Average     0.022931
11          Body Mass Index     0.228935
12                Education     0.069212
13                 Children     0.353947
14                     Pets    -0.289003

# Interpreting the Coeff

In [213]:
conclude_df["Odds_ratio"]=np.exp(conclude_df.Coefficient)
conclude_df

                   Features  Coefficient  Odds_ratio
0                 Intercept    -1.527267    0.217128
1                   Reason1     2.725613   15.265765
2                   Reason2     0.722391    2.059352
3                   Reason3     2.771122   15.976544
4                   Reason4     0.761853    2.142241
5               Month value     0.028391    1.028798
6               Day of week    -0.050733    0.950532
7    Transportation Expense     0.668129    1.950585
8          Distance to Work    -0.051281    0.950011
9                       Age    -0.104288    0.900966
10  Daily Work Load Average     0.022931    1.023196
11          Body Mass Index     0.228935    1.257261
12                Education     0.069212    1.071663
13                 Children     0.353947    1.424679
14                     Pets    -0.289003    0.749010

In [214]:
conclude_df=conclude_df.sort_values("Odds_ratio",ascending=False) #Odds ratio max to min 
conclude_df  #Feature not important if coeff~1 or oddsratio~0   
#furture away from 0 a coeff is, the bigger its important

                   Features  Coefficient  Odds_ratio
3                   Reason3     2.771122   15.976544
1                   Reason1     2.725613   15.265765
4                   Reason4     0.761853    2.142241
2                   Reason2     0.722391    2.059352
7    Transportation Expense     0.668129    1.950585
13                 Children     0.353947    1.424679
11          Body Mass Index     0.228935    1.257261
12                Education     0.069212    1.071663
5               Month value     0.028391    1.028798
10  Daily Work Load Average     0.022931    1.023196
6               Day of week    -0.050733    0.950532
8          Distance to Work    -0.051281    0.950011
9                       Age    -0.104288    0.900966
14                     Pets    -0.289003    0.749010
0                 Intercept    -1.527267    0.217128

#from the table we can assume that 'Education, Month value, Daily work load, Distance to work ' is close to 0 => smallest impact
#reason 1 = various diseases
#reason 2 = pregnancy and giving birth
#reason 3= poisoning
#reason 4 = light diseases

#get P-value , and elliminate coeff with p-valu>0.05

# Testing the model

In [215]:
reg.score(X_test,y_test)

0.7885714285714286

In [216]:
model_output #X_train

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0])

In [217]:
predict_prob = reg.predict_proba(X_test) #find prob of being 0(1st col) and 1(2nd col) 
predict_prob

array([[0.46390531, 0.53609469],
       [0.74657948, 0.25342052],
       [0.65704796, 0.34295204],
       [0.86619238, 0.13380762],
       [0.28500586, 0.71499414],
       [0.54656048, 0.45343952],
       [0.08868228, 0.91131772],
       [0.75251942, 0.24748058],
       [0.73311966, 0.26688034],
       [0.81955923, 0.18044077],
       [0.1147332 , 0.8852668 ],
       [0.82050293, 0.17949707],
       [0.48841269, 0.51158731],
       [0.81632856, 0.18367144],
       [0.30196424, 0.69803576],
       [0.09180965, 0.90819035],
       [0.74054813, 0.25945187],
       [0.65104546, 0.34895454],
       [0.79311363, 0.20688637],
       [0.30036888, 0.69963112],
       [0.09304042, 0.90695958],
       [0.73684474, 0.26315526],
       [0.26453952, 0.73546048],
       [0.16379684, 0.83620316],
       [0.40146996, 0.59853004],
       [0.25143224, 0.74856776],
       [0.39674728, 0.60325272],
       [0.5715094 , 0.4284906 ],
       [0.285085  , 0.714915  ],
       [0.7306519 , 0.2693481 ],
       [0.77989478, 0.22010522],
       [0.7835942 , 0.2164058 ],
       [0.08505969, 0.91494031],
       [0.78560411, 0.21439589],
       [0.40337608, 0.59662392],
       [0.78786373, 0.21213627],
       [0.24978642, 0.75021358],
       [0.08534308, 0.91465692],
       [0.1892224 , 0.8107776 ],
       [0.07563005, 0.92436995],
       [0.79518652, 0.20481348],
       [0.08169226, 0.91830774],
       [0.59114169, 0.40885831],
       [0.22466053, 0.77533947],
       [0.5029491 , 0.4970509 ],
       [0.38503367, 0.61496633],
       [0.86608645, 0.13391355],
       [0.60449421, 0.39550579],
       [0.77583681, 0.22416319],
       [0.84746097, 0.15253903],
       [0.20089189, 0.79910811],
       [0.7927987 , 0.2072013 ],
       [0.5725968 , 0.4274032 ],
       [0.25854587, 0.74145413],
       [0.25485021, 0.74514979],
       [0.32044314, 0.67955686],
       [0.2646692 , 0.7353308 ],
       [0.5688196 , 0.4311804 ],
       [0.78228429, 0.21771571],
       [0.81774421, 0.18225579],
       [0.35078893, 0.64921107],
       [0.14922228, 0.85077772],
       [0.42876118, 0.57123882],
       [0.62887123, 0.37112877],
       [0.44235428, 0.55764572],
       [0.86619238, 0.13380762],
       [0.5078581 , 0.4921419 ],
       [0.77030424, 0.22969576],
       [0.40166688, 0.59833312],
       [0.81111616, 0.18888384],
       [0.78033578, 0.21966422],
       [0.51897326, 0.48102674],
       [0.0720841 , 0.9279159 ],
       [0.74806867, 0.25193133],
       [0.74510964, 0.25489036],
       [0.29232263, 0.70767737],
       [0.58703206, 0.41296794],
       [0.40543874, 0.59456126],
       [0.66679908, 0.33320092],
       [0.08625715, 0.91374285],
       [0.74237296, 0.25762704],
       [0.82827339, 0.17172661],
       [0.37519643, 0.62480357],
       [0.58614151, 0.41385849],
       [0.161112  , 0.838888  ],
       [0.82652342, 0.17347658],
       [0.65639014, 0.34360986],
       [0.18128026, 0.81871974],
       [0.3389121 , 0.6610879 ],
       [0.57623312, 0.42376688],
       [0.23834557, 0.76165443],
       [0.78323603, 0.21676397],
       [0.33082498, 0.66917502],
       [0.08111997, 0.91888003],
       [0.0831617 , 0.9168383 ],
       [0.77041479, 0.22958521],
       [0.83172729, 0.16827271],
       [0.02902523, 0.97097477],
       [0.76432927, 0.23567073],
       [0.39539686, 0.60460314],
       [0.39938985, 0.60061015],
       [0.63905679, 0.36094321],
       [0.70842855, 0.29157145],
       [0.81983764, 0.18016236],
       [0.25670915, 0.74329085],
       [0.08247341, 0.91752659],
       [0.60684767, 0.39315233],
       [0.1489555 , 0.8510445 ],
       [0.58224465, 0.41775535],
       [0.312448  , 0.687552  ],
       [0.34118814, 0.65881186],
       [0.76199787, 0.23800213],
       [0.74555725, 0.25444275],
       [0.46563299, 0.53436701],
       [0.03050817, 0.96949183],
       [0.79370094, 0.20629906],
       [0.42402224, 0.57597776],
       [0.86725009, 0.13274991],
       [0.07652131, 0.92347869],
       [0.82217856, 0.17782144],
       [0.41517452, 0.58482548],
       [0.91295885, 0.08704115],
       [0.830602  , 0.169398  ],
       [0.41905359, 0.58094641],
       [0.69064085, 0.30935915],
       [0.58728984, 0.41271016],
       [0.74303731, 0.25696269],
       [0.57126827, 0.42873173],
       [0.78433774, 0.21566226],
       [0.74358367, 0.25641633],
       [0.10881915, 0.89118085],
       [0.77803436, 0.22196564],
       [0.02943164, 0.97056836],
       [0.58551885, 0.41448115],
       [0.86692551, 0.13307449],
       [0.86795354, 0.13204646],
       [0.59515991, 0.40484009],
       [0.318051  , 0.681949  ],
       [0.31094952, 0.68905048],
       [0.08364638, 0.91635362],
       [0.78294142, 0.21705858],
       [0.74109077, 0.25890923],
       [0.72814915, 0.27185085],
       [0.17187374, 0.82812626],
       [0.87969846, 0.12030154],
       [0.85713191, 0.14286809],
       [0.44508319, 0.55491681],
       [0.79311363, 0.20688637],
       [0.76282706, 0.23717294],
       [0.7996928 , 0.2003072 ],
       [0.77177555, 0.22822445],
       [0.29047169, 0.70952831],
       [0.08837988, 0.91162012],
       [0.13285375, 0.86714625],
       [0.84527266, 0.15472734],
       [0.16306072, 0.83693928],
       [0.90629048, 0.09370952],
       [0.7843431 , 0.2156569 ],
       [0.08247341, 0.91752659],
       [0.0839152 , 0.9160848 ],
       [0.0825053 , 0.9174947 ],
       [0.49583281, 0.50416719],
       [0.77008656, 0.22991344],
       [0.38784882, 0.61215118],
       [0.72343691, 0.27656309],
       [0.75107314, 0.24892686],
       [0.52823785, 0.47176215],
       [0.81744121, 0.18255879],
       [0.52778466, 0.47221534],
       [0.81837176, 0.18162824],
       [0.28645274, 0.71354726],
       [0.76420222, 0.23579778],
       [0.86459825, 0.13540175],
       [0.08210469, 0.91789531],
       [0.09133534, 0.90866466]])

In [218]:
predict_prob[:,0]

array([0.46390531, 0.74657948, 0.65704796, 0.86619238, 0.28500586,
       0.54656048, 0.08868228, 0.75251942, 0.73311966, 0.81955923,
       0.1147332 , 0.82050293, 0.48841269, 0.81632856, 0.30196424,
       0.09180965, 0.74054813, 0.65104546, 0.79311363, 0.30036888,
       0.09304042, 0.73684474, 0.26453952, 0.16379684, 0.40146996,
       0.25143224, 0.39674728, 0.5715094 , 0.285085  , 0.7306519 ,
       0.77989478, 0.7835942 , 0.08505969, 0.78560411, 0.40337608,
       0.78786373, 0.24978642, 0.08534308, 0.1892224 , 0.07563005,
       0.79518652, 0.08169226, 0.59114169, 0.22466053, 0.5029491 ,
       0.38503367, 0.86608645, 0.60449421, 0.77583681, 0.84746097,
       0.20089189, 0.7927987 , 0.5725968 , 0.25854587, 0.25485021,
       0.32044314, 0.2646692 , 0.5688196 , 0.78228429, 0.81774421,
       0.35078893, 0.14922228, 0.42876118, 0.62887123, 0.44235428,
       0.86619238, 0.5078581 , 0.77030424, 0.40166688, 0.81111616,
       0.78033578, 0.51897326, 0.0720841 , 0.74806867, 0.74510964,
       0.29232263, 0.58703206, 0.40543874, 0.66679908, 0.08625715,
       0.74237296, 0.82827339, 0.37519643, 0.58614151, 0.161112  ,
       0.82652342, 0.65639014, 0.18128026, 0.3389121 , 0.57623312,
       0.23834557, 0.78323603, 0.33082498, 0.08111997, 0.0831617 ,
       0.77041479, 0.83172729, 0.02902523, 0.76432927, 0.39539686,
       0.39938985, 0.63905679, 0.70842855, 0.81983764, 0.25670915,
       0.08247341, 0.60684767, 0.1489555 , 0.58224465, 0.312448  ,
       0.34118814, 0.76199787, 0.74555725, 0.46563299, 0.03050817,
       0.79370094, 0.42402224, 0.86725009, 0.07652131, 0.82217856,
       0.41517452, 0.91295885, 0.830602  , 0.41905359, 0.69064085,
       0.58728984, 0.74303731, 0.57126827, 0.78433774, 0.74358367,
       0.10881915, 0.77803436, 0.02943164, 0.58551885, 0.86692551,
       0.86795354, 0.59515991, 0.318051  , 0.31094952, 0.08364638,
       0.78294142, 0.74109077, 0.72814915, 0.17187374, 0.87969846,
       0.85713191, 0.44508319, 0.79311363, 0.76282706, 0.7996928 ,
       0.77177555, 0.29047169, 0.08837988, 0.13285375, 0.84527266,
       0.16306072, 0.90629048, 0.7843431 , 0.08247341, 0.0839152 ,
       0.0825053 , 0.49583281, 0.77008656, 0.38784882, 0.72343691,
       0.75107314, 0.52823785, 0.81744121, 0.52778466, 0.81837176,
       0.28645274, 0.76420222, 0.86459825, 0.08210469, 0.09133534])

# Save the model

In [219]:
#pickle[module] = module use to convert python to char stream 
#Pickling is used to store python objects. This means things like lists, dictionaries, class objects, and more
import pickle

In [220]:
with open ('model','wb') as file: #model=filename #wb=writebytes
    pickle.dump(reg,file) #dump = save reg in file

In [221]:
with open ('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)

In [222]:
loaded_model = pickle.load(open('model', 'rb'))
loaded_model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [223]:
#with open ('scaler', 'wb') as file:
   #     json.dump(absenteeism_scaler,file)

In [224]:
loaded_model2 = pickle.load(open('scaler', 'rb'))
loaded_model2

CustomScaler(columns=['Month value', 'Day of week', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children', 'Pets'],
       copy=None, with_mean=None, with_std=None)